name: Form.io JavaScript Forms and SDK
description: The core JavaScript Library for Form.io
author: The Form.io Developers
markdown: kramdown
highlighter: rouge
baseurl: https://formio.github.io/formio.js
exclude: [package.json, package-lock.json, bower.json, circle.yml, karma.conf.js, gulpfile.js, node_modules, bower_components, src, test, gulp, lib, config]

