name: Form.io JavaScript Forms and SDK
description: The core JavaScript Library for Form.io
author: The Form.io Developers
markdown: kramdown
highlighter: rouge
baseUrl: https://formio.github.io/formio.js
exclude: [package.json, gulpfile.js, node_modules, bower_components, src, test, gulp, lib]

