name: Release

on:
  push:
    tags:
      - '*' # This will make sure tag creations also trigger the workflow.

env:
  NODE_VERSION: 20.x
  AWS_DEFAULT_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy_to_test:
    # if: false
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - run: echo "Triggered by ${{ github.event_name }} event."
      - name: Check out repository code ${{ github.repository }} on ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Setup Ruby and Install Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Jekyll
        run: gem install jekyll

      - name: Restore node modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install awscli
        run: |
          sudo apt-get update
          sudo apt install -y awscli

      - name: Release
        uses: borales/actions-yarn@v4
        with:
          cmd: release
